#!/bin/bash

#начнём

case $1 in
debug)
echo
shift
;;
*)
exec 2>/dev/null
;;
esac

function datem {
date=$(date)
echo '[' $date ']:' $1 ; }


function main {
message 'Назначение системных переменных...'
export DISPLAY=:1
export USER=vnc 
message 'Запуск сервера...'
USER=vnc vncserver -geometry 1280x720 :1
datem 'xserver запущен'
message 'Запуск openbox...'
DISPLAY=:1 openbox & >&2
message 'Запуск lxpanel...'
DISPLAY=:1 lxpanel & >&2
message 'Запуск nautilus...'
DISPLAY=:1 nautilus & >&2
message 'enter, чтобы разблок. shell'
message 'Запуск zenity...'
function m {
a=$(DISPLAY=:1 zenity --forms --title="tvsgui" \
        --text="сеанс tvsgui" \
        --separator="," \
        --text="введите exit для безопастного отключения сеанса " \
        --add-entry="команда" & >&2)
        a &

}

function a {
case $a in

exit)
tvsgui exit
;;

*)
m &
;;
esac
}

m &
}



function message {
echo "[tvsgui] message:"  $1 ; }



function list {
echo '[list]' $1  ; }



function quest {
echo '[question]:' $1
read ban
case $ban in
y)
echo 
;;
*)
message 'отменено пользователем'
exit 0 
;;
esac
}


case $1 in
stop)
vncserver -kill :1
;;

exit)
tvsgui stop
;;

help)
message 'tvsgui 8 by tvsclass'
echo Параметры использования:
echo
echo tvsgui exit - отключит сервер
echo tvsgui start - включит сервер
;;

start)
main
;;

*)
echo '[tvsgui] message:' опция $1 не найдена
message 'tvsgui help' для справки
;;

esac

